$(document).ready(function(){
$('#searchText').typefast({
urlstart:"https://en.wikipedia.org/w/api.php?action=opensearch&search=",
urlend:"&format=json&callback=?",
textHighlight:true,
mouseEvent:true,
keyboardEvent:false,
autocomplete:true
});
$('#searchText1').typefast({
urlstart:"http://35.154.56.172/api/project-search/Gurgaon/",
urlend:"/Flats",
mouseEvent:true,
keyboardEvent:true,
autocomplete:false,
keyArr:'data',
key:'name'
});
})
